version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: car-rent
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=order-system
    volumes:
      - pgdata:/data/postgres
volumes:
  pgdata:
    driver: local
