version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: orders-system
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
    volumes:
      - pgdata:/data/postgres
volumes:
  pgdata:
    driver: local
