version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: orders-system
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres54321
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/data/postgres
volumes:
  pgdata:
    driver: local
